export const Constantes={
 
//ESTADOS
    ESTADO_HABILITADO : '1',
    ESTADO_DESHABILITADO : '2', 

//BOTONES
    BOTON_ACEPTAR : 'ACEPTAR',
    BOTON_CANCELAR : 'CANCELAR',
    BOTON_REGISTRAR : 'REGISTAR',
    BOTON_INICIAR_SESION : 'LOGIN',
    BOTON_ATRAS : 'ATRÁS',
    BOTON_SIGUIENTE : 'SIGUIENTE',
    BOTON_SALIR : 'SALIR',
    BOTON_RECUPERAR_CUENTA: 'RECUPERAR',
    BOTON_MODIFICAR: 'MODIFICAR',

//DIALOGS
    TITLE_ELIMINAR_USUARIO: 'Eliminar Usuario',
    PREGUNTA_ELIMINAR_USUARIO: '¿Desea eliminar el usuario?',
    TITLE_ELIMINAR_CATEGORIA: 'Eliminar Categoria',
    PREGUNTA_ELIMINAR_CATEGORIA: '¿Desea eliminar la categoria?',
    TITLE_ELIMINAR_SUBCATEGORIA: 'Eliminar SubCategoria',
    PREGUNTA_ELIMINAR_SUBCATEGORIA: '¿Desea eliminar la sub-categoria?',
    TITLE_ELIMINAR_PRODUCTO: 'Eliminar Producto',
    PREGUNTA_ELIMINAR_PRODUCTO: '¿Desea eliminar el producto?',
    TITLE_ASIGNAR_SUBCATEGORIA: 'Asignar SubCategoria',
    PREGUNTA_ASIGNAR_SUBCATEGORIA: '¿Desea asignar la sub-categoria?',
    TITLE_DESASIGNAR_SUBCATEGORIA: 'Desasignar SubCategoria',
    PREGUNTA_DESASIGNAR_SUBCATEGORIA: '¿Desea desasginar la sub-categoria?',
    TITLE_ASIGNAR_PRODUCTO: 'Asignar Producto',
    PREGUNTA_ASIGNAR_PRODUCTO: '¿Desea asignar el producto?',
    TITLE_DESASIGNAR_PRODUCTO: 'Desasignar Producto',
    PREGUNTA_DESASIGNAR_PRODUCTO: '¿Desea desasginar el producto?',
    TITLE_ELIMINAR_LISTA_PRECIO: 'Eliminar Lista de Precios',
    PREGUNTA_ELIMINAR_LISTA_PRECIO: '¿Desea eliminar la lista de precios?',
    TITLE_EDITAR_PRECIO_LISTA: 'Editar Precio',
    DESCRIPCION_EDITAR_PRECIO_LISTA: 'Configure los precios',
    TITLE_ELIMINAR_COMBO: 'Eliminar Combo',
    PREGUNTA_ELIMINAR_COMBO: '¿Desea eliminar el combo?',
    TITLE_ELIMINAR_PRODUCTO_COMBO: 'Eliminar Producto Combo',
    PREGUNTA_ELIMINAR_PRODUCTO_COMBO: '¿Desea eliminar producto del combo?',
    TITLE_ASIGNAR_PRODUCTO_COMBO: 'Asignar Producto Combo',
    PREGUNTA_ASIGNAR_PRODUCTO_COMBO: '¿Desea asignar el producto al combo?',
    TITLE_ABRIR_CAJA: 'Abrir Caja',
    PREGUNTA_ABRIR_CAJA: '¿Desea abrir la caja?',
    TITLE_CERRAR_CAJA: 'Cerrar Caja',
    PREGUNTA_CERRAR_CAJA: '¿Desea cerrar la caja?',
    TITLE_CANCELAR_COMPRA: 'Cancelar Compra',
    PREGUNTA_CANCELAR_COMPRA: '¿Desea cancelar la compra?',

//OPCIONES DIALOGS
    OPCION_ACEPTAR: 'Aceptar',

//LINKS
    LINK_REGISTRAR : 'Registrarse',
    LINK_OLVIDO_CONTRASENIA : '¿Olvido su contraseña?',

//LABELS HOME
    LABEL_HOME_PRODUCTO : 'PRODUCTO',
    LABEL_HOME_CATEGORIA : 'CATEGORIA',
    LABEL_HOME_CATEGORIA_DETALLE : 'CATEGORIA DETALLE',
    LABEL_HOME_SUB_CATEGORIA: 'SUB-CATEGORIA',
    LABEL_HOME_USUARIO : 'USUARIO',
    LABEL_HOME_COMBO : 'COMBO',

//ESTADOS
    ESTADO_ABIERTA : 'Abierta',
    ESTADO_CERRADA : 'Cerrada',

//LABELS
    LABEL_USUARIO : 'Usuario',
    LABEL_CONTRASENIA : 'Contraseña',
    LABEL_REPETIR_CONTRASENIA : 'Repetir Contraseña',
    LABEL_INICIAR_SESION : 'Iniciar Sesión',
    LABEL_REGISTRAR_USUARIO : 'Registar Usuario',
    LABEL_RECUPERAR_CUENTA : 'Recuperar Cuenta',
    LABEL_DATOS_PERSONALES: 'Datos Personales',
    LABEL_DATOS_USUARIO: 'Datos Usuario',
    LABEL_DATOS_RECUPERACION: 'Datos Recuperación',
    LABEL_RESUMEN: 'Resumen',
    LABEL_DATOS_OBLIGATORIOS :'Los campos con (*) son obligatorios',
    LABEL_PASO_1: 'Paso 1',
    LABEL_PASO_2: 'Paso 2',
    LABEL_PASO_3: 'Paso 3',
    LABEL_NOMBRE : 'Nombre',
    LABEL_APELLIDO : 'Apellido',
    LABEL_DESCRIPCION : 'Descripción',
    LABEL_CODIGO : 'Código',
    LABEL_PREGUNTA_SEGURIDAD : 'Pregunta de Seguridad',
    LABEL_RESPUESTA_PREGUNTA_SEGURIDAD : 'Respuesta de Seguridad',
    LABEL_PERFIL_USUARIO : 'Perfil Usuario',
    LABEL_EDITAR_USUARIO : 'Editar Usuario',
    LABEL_ELIMINAR_USUARIO : 'Eliminar Usuario',
    LABEL_CAMBIAR_CONTRASENIA : 'Cambiar Contraseña',
    LABEL_HOME_SISTEMA: 'Home Sistema',
    LABEL_MODIFICAR_USUARIO : 'Modificar Usuario',
    LABEL_MODIFICAR_CONTRASENIA : 'Modificar Contraseña',
    LABEL_DATOS_NUEVA_CONTRASENIA : 'Datos Nueva Contraseña',
    LABEL_CONTRASENIA_ACTUAL : 'Contraseña Actual',
    LABEL_CONTRASENIA_NUEVA : 'Contraseña Nueva',
    LABEL_NAVEGAR_CATEGORIA : 'Ir a Categoria',
    LABEL_NAVEGAR_ATRAS : 'Volver',
    LABEL_NAVEGAR_SUBCATEGORIA : 'Ir a Sub-Categoria',
    LABEL_NAVEGAR_PRODUCTO : 'Ir a Producto',
    LABEL_NAVEGAR_USUARIO : 'Ir a Usuario',
    LABEL_CATEGORIA : 'Categoria',
    LABEL_CATEGORIA_DETALLE : 'Categoria Detalle',
    LABEL_AGREGAR_CATEGORIA : 'Agregar Categoria',
    LABEL_EDITAR_CATEGORIA : 'Editar Categoria',
    LABEL_ELIMINAR_CATEGORIA : 'Eliminar Categoria',
    LABEL_MODIFICAR_CATEGORIA: 'Modificar Categoria',
    LABEL_HABILITAR_CATEGORIA: 'Habilitar Categoria',
    LABEL_DATOS_CATEGORIA: 'Datos Categoria',
    LABEL_REGISTRAR_CATEGORIA: 'Registrar Categoria',
    LABEL_BUSCAR_TABLA_CATEGORIA : 'Ingrese el nombre de la categoria',
    LABEL_ACCION : 'Acción',
    LABEL_SUBCATEGORIASUBCATEGORIAS_CATEGORIA: 'SubCategorias de Categoria',
    LABEL_PRODUCTOS_CATEGORIA: 'Productos de Categoria',
    LABEL_SUBCATEGORIA : 'SubCategoria',
    LABEL_SUBCATEGORIA_DETALLE : 'SubCategoria Detalle',
    LABEL_AGREGAR_SUBCATEGORIA : 'Agregar SubCategoria',
    LABEL_EDITAR_SUBCATEGORIA : 'Editar SubCategoria',
    LABEL_ELIMINAR_SUBCATEGORIA : 'Eliminar SubCategoria',
    LABEL_MODIFICAR_SUBCATEGORIA: 'Modificar SubCategoria',
    LABEL_HABILITAR_SUBATEGORIA: 'Habilitar SubCategoria',
    LABEL_DATOS_SUBCATEGORIA: 'Datos SubCategoria',
    LABEL_ASIGNAR_SUBCATEGORIA : 'Asignar SubCategoria',
    LABEL_DESASGINAR_SUBCATEGORIA : 'Desasignar SubCategoria',
    LABEL_REGISTRAR_SUBCATEGORIA: 'Registrar SubCategoria',
    LABEL_BUSCAR_TABLA_SUBCATEGORIA : 'Ingrese el nombre de la sub-categoria',
    LABEL_PRODUCTOS_SUBCATEGORIA: 'Productos de SubCategoria',
    LABEL_PRODUCTO : 'Producto',
    LABEL_PRODUCTO_DETALLE : 'Producto Detalle',
    LABEL_AGREGAR_PRODUCTO : 'Agregar Producto',
    LABEL_EDITAR_PRODUCTO : 'Editar Producto',
    LABEL_ELIMINAR_PRODUCTO : 'Eliminar Producto',
    LABEL_MODIFICAR_PRODUCTO: 'Modificar Producto',
    LABEL_HABILITAR_PRODUCTO: 'Habilitar Producto',
    LABEL_DATOS_PRODUCTO: 'Datos Producto',
    LABEL_REGISTRAR_PRODUCTO: 'Registrar Producto',
    LABEL_ASIGNAR_PRODUCTO : 'Asignar Producto',
    LABEL_DESASGINAR_PRODUCTO : 'Desasignar Producto',
    LABEL_BUSCAR_TABLA_PRODUCTO : 'Ingrese el nombre del producto',
    LABEL_MARCA: 'Marca',
    LABEL_UNIDAD_MEDIDA: 'Unidad Medida',
    LABEL_MEDIDA: 'Medida',
    LABEL_UPDATE_TABLA: 'Actualizar Tabla',
    LABEL_LISTA_PRECIO: 'Lista de Precios',
    LABEL_AGREGAR_LISTA_PRECIO: 'Agregar Lista de Precios',
    LABEL_BUSCAR_TABLA_LISTA_PRECIO: 'Ingrese el nombre del producto',
    LABEL_PRECIO_COMPRA : 'Precio Compra',
    LABEL_PRECIO_VENTA : 'Precio Venta',
    LABEL_MARGEN_GANANCIA : 'Margen Ganancia',
    LABEL_GANANCIA : 'Ganancia',
    LABEL_PESO : '$',
    LABEL_PORCENTAJE: '%',
    LABEL_ELIMINAR_LISTA_PRECIO : 'Eliminar Lista de Precios',
    LABEL_REGISTRAR_LISTA_PRECIO : 'Registrar Lista de Precios',
    LABEL_DATOS_LISTA_PRECIO : 'Datos Lista de Precios',
    LABEL_BUSCAR_PRODUCTO: 'Buscar Producto',
    LABEL_EDITAR_PRECIO: 'Editar Precio',
    LABEL_AGREGAR_COMBO: 'Agregar Combo',
    LABEL_EDITAR_COMBO: 'Editar Combo',
    LABEL_ELIMINAR_COMBO: 'Eliminar Combo',
    LABEL_REGISTRAR_COMBO: 'Registrar Combo',
    LABEL_DATOS_COMBO: 'Datos Combo',
    LABEL_COMBO: 'Combo',
    LABEL_BUSCAR_TABLA_COMBO: 'Ingrese el nombre del combo',
    LABEL_PRODUCTOS_COMBO: 'Productos Combo',
    LABEL_NAVEGAR_COMBO: 'Ir a Combo',
    LABEL_CANTIDAD: 'Cantidad',
    LABEL_COMBO_DETALLE: 'Combo Detalle',
    LABEL_MODIFICAR_COMBO: 'Modificar Combo',
    LABEL_CAJA: 'Caja',
    LABEL_DETALLE_CAJA: 'Detalle Caja',
    LABEL_FECHA_APERTURA: 'Fecha Apertura',
    LABEL_FECHA_CIERRE: 'Fecha Cierre',
    LABEL_TOTAL_APERTURA: 'Total Apertura',
    LABEL_TOTAL_CIERRE: 'Total Cierre',
    LABEL_ABRIR_CAJA: 'Abrir Caja',
    LABEL_CERRAR_CAJA: 'Cerrar Caja',
    LABEL_TOTAL_INGRESOS: 'Total Ingresos',
    LABEL_DETALLE_INGRESOS: 'Detalle Ingresos',
    LABEL_TOTAL_EGRESOS: 'Total Egresos',
    LABEL_DETALLE_EGRESOS: 'Detalle Egresos',
    LABEL_BALANCE : 'Balance',
    LABEL_TOTAL : 'Total',
    LABEL_FECHA: 'Fecha',
    LABEL_MOVIMIENTO_ENTRADA: 'Entrada',
    LABEL_MOVIMIENTO_SALIDA: 'Salida',
    LABEL_FECHA_CIERRE_SIN_DEFINIR : 'Sin Definir',
    LABEL_TOTAL_PARCIAL : 'Total Parcial',
    LABEL_DESCUENTO : 'Descuento',
    LABEL_TIPO_MOVIMIENTO : 'Tipo Movimiento',
    LABEL_ESTADO : 'Estado',
    LABEL_BUSCAR_TABLA_COMPRA : 'Ingrese el usuario de la compra',
    LABEL_NAVEGAR_COMPRA : 'Ir a Compra',
    LABEL_AGREGAR_COMPRA : 'Agregar Compra',
    LABEL_CANCELAR_COMPRA : 'Cancelar Compra',
    LABEL_COMPRA : 'Compra',
    LABEL_BUSCAR_COMPRA: 'Buscar Compra',
    LABEL_REGISTRAR_COMPRA: 'Registrar Compra',

//DESCRIPCIÓN CARD 
    DESCRIPCION_PRODUCTO : 'En esta sección se lleva a cabo la administración de los productos',
    DESCRIPCION_CATEGORIA : 'En esta sección se lleva a cabo la administración de las categorias',
    DESCRIPCION_CATEDESCRIPCION_CATEGORIA : 'En esta sección se lleva a cabo la administración de las categorias',
    DESCRIPCION_SUB_CATEGORIA : 'En esta sección se lleva a cabo la administración de las sub-categorias',
    DESCRIPCION_SUB_CATEGORIA_CATEGORIA : 'En esta sección se lleva a cabo la administración de las sub-categorias de la categoria seleccionada',
    DESCRIPCION_SUBCATEGORIAS_NO_CATEGORIA : 'La siguiente tabla contiene subcategorias que no han sido asignadas a la categoria seleccionada',
    DESCRIPCION_PRODUCTO_CATEGORIA : 'En esta sección se lleva a cabo la administración de los productos de la categoria seleccionada',
    DESCRIPCION_PRODUCTOS_NO_CATEGORIA : 'La siguiente tabla contiene productos que no han sido asignados a la categoria seleccionada',
    DESCRIPCION_PRODUCTO_SUBCATEGORIA : 'En esta sección se lleva a cabo la administración de los productos de la sub-categoria seleccionada',
    DESCRIPCION_PRODUCTOS_NO_SUBCATEGORIA : 'La siguiente tabla contiene productos que no han sido asignados a la sub-categoria seleccionada',
    DESCRIPCION_USUARIO: 'En esta sección se lleva a cabo la administración de los usuarios',
    DESCRIPCION_LISTA_PRECIO : 'En esta sección se lleva a cabo la administración de listas de precios',
    DESCRIPCION_COMBO: 'En esta sección se lleva a cabo la administración de los combos',
    DESCRIPCION_LISTA_PRECIO_COMBO: 'En esta sección se pueden seleccionar los productos que van a componer el combo',
    DESCRIPCION_CAJA: 'En esta sección se lleva a cabo la administración de la caja',
    LABEL_DETALLE_COMPRA : 'En esta sección se lleva a cabo la administración de las compras',


//ERRORES
    ERROR_CAMPOS_INCOMPLETOS : 'Debe completar todos los campos obligatorios (*)',
    ERROR_CONTRASENIAS_DISTINTAS : 'Las contraseñas deben coincidir',
    ERROR_USUARIO_CONTRASENIA_IGUAL:'El nombre de usuario y contraseña debe ser diferente',
    ERROR_CONTRASENIAS_IGUAL:'La contraseña nueva debe ser diferente a la actual',
    ERROR_NO_INICIO_SESION : 'El usuario no inicio sesion',
    ERROR_LISTAS_DIFERENTES : 'Debe completar todas las filas de la lista de precios',

    
//MENSAJES
    MENSAJE_INICIO_SISTEMA : 'Bienvenido a CrazyBeer',
    MENSAJE_REGISTRACION_EXITOSA : 'Registración Exitosa',
    MENSAJE_RECUPERACION_EXITOSA : 'Recuperación Exitosa',
    MENSAJE_MODIFICACION_EXITOSA : 'Modificación Exitosa',
    MENSAJE_NO_INICIO_SESION: 'La sesión expiro, ingrese nuevamente',
    MENSAJE_USUARIO_ELIMINADO: 'Usuario eliminado correctamente',
    MENSAJE_CATEGORIA_ELIMINADA: 'Categoria eliminada correctamente',
    MENSAJE_SUBCATEGORIA_ELIMINADA: 'SubCategoria eliminada correctamente',
    MENSAJE_PRODUCTO_ELIMINADO: 'Producto eliminado correctamente',
    MENSAJE_ASIGNACION_EXISTOSA: 'Asignación Exitosa',
    MENSAJE_DESASIGNACION_EXISTOSA: 'Desasignación Exitosa',
    MENSAJE_LISTA_PRECIO_ELIMINADA: 'Lista de Precios eliminada correctamente',
    MENSAJE_COMBO_ELIMINADO: 'Combo eliminado correctamente',
    MENSAJE_REGISTRACION_APERTURA: 'Apertura Exitosa',
    MENSAJE_REGISTRACION_CIERRE: 'Cierre Exitoso',
    MENSAJE_OK : 'OK',

//OPERADORES COMPARACION
    OPERADOR_IGUAL : 'IGUAL',
    OPERADOR_MAYOR : 'MAYOR',
    OPERADOR_MAYOR_IGUAL: 'MAYOR_IGUAL',
    OPERADOR_MENOR : 'MENOR',
    OPERADOR_MENOR_IGUAL : 'MENOR_IGUAL',
    OPERADOR_DISTINTO : 'DISTINTO',

//URLS
    URL_LOGIN : '/login/',
    URL_HOME : '/home/',
    URL_PERFIL : '/profile/',
    URL_REGISTRAR_USUARIO : '/addUser/',
    URL_RECUPERAR_CUENTA: '/recoverAccount/',
    URL_HOME_CATEGORIA: '/homeCategory/',
    URL_HOME_CATEGORIA_DETALLE: '/homeCategoryDetail/',
    URL_ASIGNAR_SUBCATEGORIA: '/assignSubCategory/',
    URL_EDITAR_CATEGORIA: '/editCategory/',
    URL_AGREGAR_CATEGORIA: '/addCategory/',
    URL_HOME_SUBCATEGORIA: '/homeSubCategory/',
    URL_HOME_SUBCATEGORIA_DETALLE: '/homeSubCategoryDetail/',
    URL_EDITAR_SUBCATEGORIA: '/editSubCategory/',
    URL_AGREGAR_SUBCATEGORIA: '/addSubCategory/',
    URL_HOME_PRODUCTO: '/homeProduct/',
    URL_HOME_PRODUCTO_DETALLE: '/homeProductDetail/',
    URL_EDITAR_PRODUCTO: '/editProduct/',
    URL_AGREGAR_PRODUCTO: '/addProduct/',
    URL_ASIGNAR_PRODUCTO_CATEGORIA: '/assignProductCategory/',
    URL_ASIGNAR_PRODUCTO_SUBCATEGORIA: '/assignProductSubCategory/',
    URL_HOME_LISTA_PRECIO : '/homePriceList/',
    URL_AGREGAR_LISTA_PRECIO : '/addPriceList/',
    URL_HOME_COMBO: '/homeCombo/',
    URL_HOME_COMBO_DETALLE: '/homeComboDetail/',
    URL_AGREGAR_COMBO : '/addCombo/',
    URL_EDITAR_COMBO: '/editCombo/',
    URL_HOME_CAJA: '/homeCash/',
    URL_HOME_COMPRA: '/homeBuy/',
    URL_HOME_COMPRA_DETALLE: '/homeComboBuy/',
    URL_AGREGAR_COMPRA : '/addBuy/',
};